GalleryProject/GalleryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
    #path('blog/', include('blog.urls')),
    path('user_system/', include('django.contrib.auth.urls')),
    path('user_system/', include('user_system.urls')),
    path('gallery/', include('gallery.urls')),
    path('client/', include('client.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GalleryProject/client/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from . import views

urlpatterns = [
  path('o-panel/', views.o_client, name='o-client'),
  path('o-panel/invite', InviteView.as_view(), name='invite'),
  
  path('o-panel/binder/project/', views.project_main, name='o-project'),
  path('o-panel/binder/project/<slug:slug>', views.project_details, name='o-project-details'),
  
  path('o-panel/binder/project/events/<int:year>/<str:month>', views.clandar, name='project-calendar'),
  path('o-panel/binder/project/events/new', views.clandar, name='new-event'),
  
  path('o-panel/binder/project/requests/', views.project_request, name='o-reqeust'),
  path('o-panel/binder/project/requests/<slug:slug>', views.project_request_details, name='request-details'),
  path('o-panel/binder/project/request/approval/<slug:slug>', views.request_approval, name='request-approval'),

  path('c-panel/binder/<int:id>', views.c_panel, name='c-panel'),
  path('c-panel/binder/new-request', ClienRequestCreate.as_view(), name='project-request'),
  path('c-panel/binder/requests/<slug:slug>',views.request_status, name='request-status'),
  path('c-panel/binder/project/<slug:slug>/',views.client_project_details, name='c-project-details'),
]   
  

GalleryProject/site_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', views.index_page, name='index'),
    path('social/', views.social_page, name='social'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/success/<int:pk>/', ContactSuccess.as_view(), name='contact-success'),      
    path('error/<int:status>/<slug:error_message>', views.error_logger, name='issue-backend'),     
    
    path('o-panel', views.o_main, name='o_panel'),
    path('o-panel/binder', views.o_binder, name='binder'),
    path('o-panel/marketing', views.marketing, name='marketing'),
    path('o-panel/gallery', views.o_gallery, name='o-gallery'),
    
    path('o-panel/settings/documents', views.document_settings, name='o-documents'),
]

GalleryProject/client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from GalleryProject.env.app_Logic.untility.quick_tools import DateFunction
df = DateFunction()

class Client(models.Model):
    name = models.CharField(max_length=255)
    strip_id = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=10, verbose_name='Contact Phone Number')
    email = models.EmailField(max_length=100, verbose_name='Email Address')
    address_1 = models.CharField(max_length=255, verbose_name='Street Address/PO Box')
    address_2 = models.CharField(max_length=255, verbose_name='Apt/Suite')
    city = models.CharField(max_length=255, verbose_name='City')
    state = models.CharField(max_length=255, verbose_name='State')
    zip_code =models.CharField(max_length=255, verbose_name='Zipcode')
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("client-details", args=(self.id))

class Project(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255, default='Pending Deposit')
    client_id = models.ForeignKey(Client, null=True, blank=True, on_delete=models.SET_NULL)
    slug = models.SlugField(null=False, unique=True)
    documents = models.ManyToManyField('site_app.Document')

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("project-details", kwargs={"slug": self.slug})
    
class Invite(models.Model):
    name = models.CharField(max_length=255, verbose_name='Name')
    email = models.EmailField(max_length=100, verbose_name='Email Address' )
    hexkey = models.CharField(max_length=32)
    used = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("project-binder", args=(str(self.id)))
    
    
class ProjectRequest(models.Model):
    name = models.CharField(max_length=255, verbose_name='Project Name')
    client_id = models.ForeignKey(Client, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.CharField(max_length=10)
    scope = models.CharField(max_length=255, verbose_name='Project-Type/Scope')
    details = models.CharField(max_length=3000, verbose_name='Project Details')
    slug = models.SlugField(null=False, unique=True, max_length=32)
    location = models.CharField(max_length=255, verbose_name='Location type')
    status = models.CharField(max_length=25, default='pending')

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        
        return reverse("request-status", kwargs={"slug": self.slug})
    
class RequestReply(models.Model):
    project_request_id = models.ForeignKey(ProjectRequest, null=True, blank=True, on_delete=models.SET_NULL)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    comment = models.CharField(max_length=3000)
    date_posted = models.DateField(auto_now=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return str(self.project_request_id) + ' | ' + str(self.user_id)

    def get_absolute_url(self):
        
        return reverse("request-status", args=(str(self.id)))
    
class ProjectTerms(models.Model):
    project_request_id = models.ForeignKey(ProjectRequest, null=True, blank=True, on_delete=models.SET_NULL)
    project_id = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    scope = models.CharField(max_length=255)
    services = models.TextField(max_length=5000, blank=True)
    project_cost = models.FloatField(default='600.00')
    deposit = models.FloatField(default='0.00')

    def __str__(self):
        return str(self.project_request_id) + ' | ' + str(self.user_id)

    def get_absolute_url(self):
        
        return reverse("request-approval", args=(str(self.id)))
    
    
class ProjectEvents(models.Model):
    title = models.CharField(max_length=255)
    billing_id = models.ForeignKey('user_system.Invoice', null=True, blank=True, on_delete=models.SET_NULL)
    project_id = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.DateField(auto_now=False, default=df.date_now())
    start = models.TimeField(blank=True, null=True)
    end = models.TimeField(blank=True, null=True)
    event_type = models.CharField(max_length=50, blank=True)
    details = models.CharField(max_length=500, blank=True)

    
    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        date = df.date_now()
        year, month, day = date.split('-')
        return reverse("project-calendar", args=(year, month))
    
class Note(models.Model):
    project_id = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    note = models.TextField(max_length=3000)
    date_posted = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        
        return reverse("project-notes", args=(str(self.project_id)))

GalleryProject/site_app/models.py
from django.db import models
from django.urls import reverse

doc_type_choice = [
    ('site', 'site'),
    ('client', 'client'),
]
doc_kind = [
    ('pdf', 'pdf'),
    ('docx', 'docx'),
    ]

#-------------------------------------------------------------------------------------------------------#
# models class
#-------------------------------------------------------------------------------------------------------#

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=255)
    body = models.TextField(max_length=800)

    def __str__(self):
        return f'Name: {self.name} - Subject: {self.subject}'
    
    def get_absolute_url(self):
        return reverse("contact-success")
    
class Document(models.Model):
    name = models.CharField(max_length=50)
    file_path = models.CharField(max_length=255, null=True, blank=True)
    doc_type = models.CharField(choices=doc_type_choice, null=True, blank=True, max_length=50)
    doc_content = models.TextField(max_length=None, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)
    kind = models.CharField(choices=doc_kind, null=True, blank=True, max_length=50)
    created = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse("o-documnents")

GalleryProject/site_app/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your Email'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'body' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Message Body'}),
        }

GalleryProject/site_app/views.py
from typing import Any
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.views.generic.edit import FormView
from django.db.models import Q
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Contact, Document
from gallery.models import Image, Dispaly
from client.models import Project, Client
from .forms import ContactForm
from GalleryProject.env.app_Logic.smtp.MailerDJ import AutoReply
from GalleryProject.env.cloudflare_API.CFAPI import APICall
from GalleryProject.env.app_Logic.date_time_calendar import cal_gen, date_passed_check
import random
from pathlib import Path
import os
from dotenv import load_dotenv
from GalleryProject.env.app_Logic.json_utils import DataSetUpdate
from GalleryProject.env.app_Logic.smtp.MailerDJ import AutoReply
from GalleryProject.env.app_Logic.untility.quick_tools import QuickStripe, DateFunction, Hexer
from log_app.logging_config import logging
import time
from random import shuffle
from django.utils.text import slugify
qs = QuickStripe()
df = DateFunction()
hexer = Hexer()
smtp_request = AutoReply()
dataQ = DataSetUpdate()

#-----------------------------------------------------------------------------------------------------------#
#
# functions
#
#-----------------------------------------------------------------------------------------------------------#


def append_cloundflare_id(cf_id, image_id, type_image):
	update_image_record = Image.objects.get(id=image_id)
	
	image_url = 'https://imagedelivery.net/4_y5kVkw2ENjgzV454LjcQ/' + cf_id +'/display'
	update_image_record.image_link = image_url
	update_image_record.save()


#-------------------------------------------------------------------------------------------------------#
# index - booking - galler - about 
#-------------------------------------------------------------------------------------------------------#


def index_page(request):
	all_images = Image.objects.all()
	image_list = Image.objects.filter(display=1)[:50]
	

	image1 = all_images.filter(display=3).first()

	image2 = all_images.filter(display=5).first()

	image3 = all_images.filter(display=7).first()

	return render(request, 'index.html', 
				  {
					'image_list': image_list,
					'image1':image1,
					'image2':image2,
					'image3':image3,
					})

def social_page(request):
	return render(request, 'social.html')

class ContactView(FormView):
	model = Contact
	template_name = 'contact.html'
	form_class = ContactForm
	
	def form_valid(self, form):
		self.object = form.save()
		name = self.object.name
		email = self.object.email
		subject = self.object.subject
		body = self.object.body
		idN = self.object.pk

		email_sent = smtp_request.contact_request(email, name, subject)
		notice_sent = smtp_request.contact_alart(email, name, subject, body)
		if email_sent == 'success' and notice_sent == 'success':

			return redirect('contact-success', pk=idN)
		else:
			e = 'email-sent ', notice_sent, 'notice-sent ', notice_sent
			logging.error("Client Invite Error: %s", str((e)))
			slugified_error_message = slugify(str(e))
			return redirect('issue-backend', status=500, error_message=slugified_error_message)
	
class ContactSuccess(DetailView):
	model = Contact
	template_name = 'success/contact-success.html'
	
def error_logger(request, status, error_message):
	
	return render(request, 'error_page/issue.html', {'status': status, 'e': error_message})
	
#-------------------------------------------------------------------------------------------------------#
# owner panel main branch
#-------------------------------------------------------------------------------------------------------#

def o_main(request):
	image_list = Image.objects.all()
	project_list = Project.objects.all()
	client_list = Client.objects.all()
	gal1 = Image.objects.filter(Q(display=4) | Q(display=3))
	gal2 = Image.objects.filter(Q(display=5) | Q(display=7))
	gal4 = Image.objects.filter(Q(display=6) | Q(display=8))
	site_image = Image.objects.filter(Q(client_id="1"))
	client_images = Image.objects.exclude(Q(client_id="1"))
	dataQ.json_chart_data()

	return render(request, 'o_panel/main.html', {
		'image_list': image_list,
		'project_list': project_list,
		'client_list': client_list,
		'gal1': gal1,
		'gal2': gal2,
		'gal4': gal4,
		'site_image': site_image,
		'client_images':client_images,
	})
	
def o_binder(request):
	month0, month, month2, cal, year, todays_date, cal_date = cal_gen()
	project_list = Project.objects.all()
	client_list = Client.objects.all()
	image_list = Image.objects.all()
	
	return render(request, 'o_panel/binder.html', {
		'image_list': image_list,
		'project_list': project_list,
		'client_list': client_list,
		'year': year,
		'month':month,
	})
	

def marketing(request):
	return render(request, 'o_panel/marketing.html')

def o_gallery(request):
	return render(request, 'o_panel/gallery.html')


def document_settings(request):
	documents = Document.objects.filter(doc_type='site')

GalleryProject/site_app/templates/c_panel/project/request/new-request.html
{% extends 'c-panel.html' %}
{% block title %}C | Project Request Form{% endblock %}
{% block content %}






<div class="sections p-p form-fit form-group">
	<h1 class='h1-1'>Project Request Form</h1>
	<form method=POST>
		{% csrf_token %}
			<p>
				<label for="id_name">Project Name:</label>
				<input type="text" name="name" class="form-control" maxlength="255" required="" id="id_name">
			</p>

			<p>
				<label for="id_date">Desired date:</label>
				<input type="date" name="date" class="form-control" required="" id="id_date">
			</p>
				
			<p>
				<label for="id_scope">Project-Type/Scope:</label>
				<select name="scope" class="form-select" maxlength="255" id="id_scope">
					<option value='' selected>Select Project Type/Scope</option>
					<option value='model'>Model photoshoot</option>
					<option value='wedding'>Wedding photoshoot</option>
					<option value='family'>Family photoshoot</option>
				</select>
			</p>

			<p>
				<label for="id_details">Project Details:</label>
					<ul>Please include any details that may help me understand your vision. </ul>

				<textarea name="details" cols="40" rows="10" class="form-control" maxlength="3000" required="" id="id_details"></textarea>
			</p>

			<p>
				<label for="id_location">Location type:</label>
				<p class='p-p'>In state, meaning within the state of Tennessee</p>
				<select type="select" name="location" class="form-select" required="" id="id_location">
					<option value='' selected>Select location type</option>
					<option value='Indoors, in-state'>Indoors, in-state</option>
					<option value='Indoors, out-of-state'>Indoors, out-state</option>
					<option value='Outdoors, in-state'>Outdoors, in-state</option>
					<option value='Outdoors, out-of-state'>Outdoors, out-state</option>
					<option value='Indoors, in-state: Photographers Pick'>Indoors, in-state: Photographers Pick</option>
					<option value='Outdoors, in-state: Photographers Pick'>Outdoors, in-state: Photographers Pick</option>
				</select>
			</p>
		<button class="btn-cust">
			Request
		</button>
	</form>
</div>

{% endblock %}

GalleryProject/site_app/templates/c_panel/project/request/request-status.html
{% extends 'c-panel.html' %}
{% block title %}Request Status{% endblock %}
{% block content %}
<div class='sections'>
	<div class='row'>
		<div class='col-6 mt-4 mb-4'>
			<div class='row mt-4 mb-4'>
				<div class='mt-4 text-center mt-4 mb-4'>
					<h1 class='nums'>
						{{projectrequest|title}}
					</h1>
					<p class='p-p'>
						Project Request
					</p>
				</div>
				<h1 class='h1-1'>
					Project Scope:
				</h1>
				<hr>
				<div class='col-12'>
					<div class='sections-2'>
						<div class='row'>
							<div class='col-3'>
								<p class='p-p'>Project-Type:</p>
								<p class='p-p'>Desired Date:</p>
								<p class='p-p'>Location type:</p>
							</div>
							<div class='col-7'>
								<p class='p-p'>{{projectrequest.scope}}</p> 
								<p class='p-p'>{{projectrequest.date}}</p> 
								<p class='p-p'>{{projectrequest.location}}</p> 
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class='col-6 mt-4 mb-4'>
			<div class='sections-2 h-100'>
				<h1 class='h1-1'>
					Requested Project Details:
				</h1>
				<hr>
				<div class="overflow-auto">
					<p class='p-p'>{{projectrequest.details}}</p>
				</div>
			</div>
		</div>

	</div>
</div>
<div class='row'>
	<div class='col-6 mt-4 mb-4'>
		<div class='sections-small'>
			<button class="btn-cust" data-bs-toggle="collapse" href="#collapse1" role="button" aria-expanded="false" aria-controls="collapse1">
				Send a Message <i class="fa-solid fa-message"></i>
			</button>
			<div class="sections-2 mt-4 mb-4 form-group">
				<div class="collapse" id="collapse1" style='width:100%'>
					<form method=POST>
						{% csrf_token %}
						{{comment_form.as_p}}
						<button class="btn-cust">
							Submit
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class='col-6 mt-4 mb-4'>
		<div class='sections-small'>
			<button class="btn-cust" data-bs-toggle="collapse" href="#collapse2" role="button" aria-expanded="false" aria-controls="collapse1">
				Project Request Thread <i class="fa-solid fa-comments"></i>
			</button>
			<div class="sections-2 mt-4 mb-4 form-group">
				<div class="collapse" id="collapse2" style='width:100%'>

					{% for comment in comments %}
					{% if comment.user_id == user %}
					<div class='col-12 mt-4 mb-4'>
						<div class='row'>
							<div class='col-12 comment-sub-box'> 
								<div class="user-content" >
									<h1 class='user-box h1-1'>
										{{ comment.user_id|title }}
									</h1>
									<p class='p-p user-box'>
										{{ comment.date_posted|title }}
									</p>
									<hr>
									<p class='p-p'>
										{{ comment.comment}}
									</p>
									<div class='comment-line-3'></div>
								</div>
							</div>
						</div>
					</div>
					{% else %}
					<div class='col-12 mt-4 mb-4'>
						<div class='row'>
							<div class='col-12 comment-sub-box'> 
								<div class="comment-content" >
									<h1 class='h1-1'>
										{{ comment.user_id|title }}
									</h1>
									<p class='p-p'>
										{{ comment.date_posted|title }}
									</p>
									<hr>
									<p class='p-p'>
										{{ comment.comment}}
									</p>
									<div class='comment-line-2'></div>
								</div>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	</div>





</div>

{% endblock %}