GalleryProject/GalleryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
    #path('blog/', include('blog.urls')),
    path('user_system/', include('django.contrib.auth.urls')),
    path('user_system/', include('user_system.urls')),
    path('gallery/', include('gallery.urls')),
    path('client/', include('client.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GalleryProject/client/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from . import views

urlpatterns = [
  path('o-panel/', views.o_client, name='o-client'),
  path('o-panel/invite', InviteView.as_view(), name='invite'),
  
  path('o-panel/binder/project/', views.project_main, name='o-project'),
  path('o-panel/binder/project/<slug:slug>', views.project_details, name='o-project-details'),
  
  path('o-panel/binder/project/events/<int:year>/<str:month>', views.clandar, name='project-calendar'),
  path('o-panel/binder/project/events/new', views.clandar, name='new-event'),
  
  path('o-panel/binder/project/requests/', views.project_request, name='o-reqeust'),
  path('o-panel/binder/project/requests/<slug:slug>', views.project_request_details, name='request-details'),
  path('o-panel/binder/project/request/approval/<slug:slug>', views.request_approval, name='request-approval'),

  path('c-panel/binder/<int:id>', views.c_panel, name='c-panel'),
  path('c-panel/binder/new-request', ClienRequestCreate.as_view(), name='project-request'),
  path('c-panel/binder/requests/<slug:slug>',views.request_status, name='request-status'),
  path('c-panel/binder/project/<slug:slug>/',views.client_project_details, name='c-project-details'),
]   
  

GalleryProject/site_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', views.index_page, name='index'),
    path('social/', views.social_page, name='social'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/success/<int:pk>/', ContactSuccess.as_view(), name='contact-success'),      
    path('error/<int:status>/<slug:error_message>', views.error_logger, name='issue-backend'),     
    
    path('o-panel', views.o_main, name='o_panel'),
    path('o-panel/binder', views.o_binder, name='binder'),
    path('o-panel/marketing', views.marketing, name='marketing'),
    path('o-panel/gallery', views.o_gallery, name='o-gallery'),
    
    path('o-panel/settings/documents', views.document_settings, name='o-documents'),
]

GalleryProject/client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from GalleryProject.env.app_Logic.untility.quick_tools import DateFunction
df = DateFunction()

class Client(models.Model):
    name = models.CharField(max_length=255)
    strip_id = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=10, verbose_name='Contact Phone Number')
    email = models.EmailField(max_length=100, verbose_name='Email Address')
    address_1 = models.CharField(max_length=255, verbose_name='Street Address/PO Box')
    address_2 = models.CharField(max_length=255, verbose_name='Apt/Suite')
    city = models.CharField(max_length=255, verbose_name='City')
    state = models.CharField(max_length=255, verbose_name='State')
    zip_code =models.CharField(max_length=255, verbose_name='Zipcode')
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("client-details", args=(self.id))

class Project(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255, default='Pending Deposit')
    client_id = models.ForeignKey(Client, null=True, blank=True, on_delete=models.SET_NULL)
    slug = models.SlugField(null=False, unique=True)
    documents = models.ManyToManyField('site_app.Document')

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("project-details", kwargs={"slug": self.slug})
    
class Invite(models.Model):
    name = models.CharField(max_length=255, verbose_name='Name')
    email = models.EmailField(max_length=100, verbose_name='Email Address' )
    hexkey = models.CharField(max_length=32)
    used = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("project-binder", args=(str(self.id)))
    
    
class ProjectRequest(models.Model):
    name = models.CharField(max_length=255, verbose_name='Project Name')
    client_id = models.ForeignKey(Client, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.CharField(max_length=10)
    scope = models.CharField(max_length=255, verbose_name='Project-Type/Scope')
    details = models.CharField(max_length=3000, verbose_name='Project Details')
    slug = models.SlugField(null=False, unique=True, max_length=32)
    location = models.CharField(max_length=255, verbose_name='Location type')
    status = models.CharField(max_length=25, default='pending')

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        
        return reverse("request-status", kwargs={"slug": self.slug})
    
class RequestReply(models.Model):
    project_request_id = models.ForeignKey(ProjectRequest, null=True, blank=True, on_delete=models.SET_NULL)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    comment = models.CharField(max_length=3000)
    date_posted = models.DateField(auto_now=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return str(self.project_request_id) + ' | ' + str(self.user_id)

    def get_absolute_url(self):
        
        return reverse("request-status", args=(str(self.id)))
    
class ProjectTerms(models.Model):
    project_request_id = models.ForeignKey(ProjectRequest, null=True, blank=True, on_delete=models.SET_NULL)
    project_id = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    scope = models.CharField(max_length=255)
    services = models.TextField(max_length=5000, blank=True)
    project_cost = models.FloatField(default='600.00')
    deposit = models.FloatField(default='0.00')

    def __str__(self):
        return str(self.project_request_id) + ' | ' + str(self.user_id)

    def get_absolute_url(self):
        
        return reverse("request-approval", args=(str(self.id)))
    
    
class ProjectEvents(models.Model):
    title = models.CharField(max_length=255)
    billing_id = models.ForeignKey('user_system.Invoice', null=True, blank=True, on_delete=models.SET_NULL)
    project_id = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.DateField(auto_now=False, default=df.date_now())
    start = models.TimeField(blank=True, null=True)
    end = models.TimeField(blank=True, null=True)
    event_type = models.CharField(max_length=50, blank=True)
    details = models.CharField(max_length=500, blank=True)

    
    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        date = df.date_now()
        year, month, day = date.split('-')
        return reverse("project-calendar", args=(year, month))
    
class Note(models.Model):
    project_id = models.ForeignKey(Project, null=True, blank=True, on_delete=models.SET_NULL)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    note = models.TextField(max_length=3000)
    date_posted = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        
        return reverse("project-notes", args=(str(self.project_id)))

GalleryProject/user_system/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse
from GalleryProject.env.app_Logic.untility.quick_tools import DateFunction
df = DateFunction()
class Coupon(models.Model):

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=8)
    percent = models.IntegerField(default=0)
    active = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse("cupon-details", kwargs={"pk": self.pk})

class credit(models.Model):

    name = models.CharField(max_length=255)
    amount = models.FloatField(max_length=8, default=0.00)
    details = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse("cupon-details", kwargs={"pk": self.pk})
    

class Invoice(models.Model):

    invoice_id = models.CharField(max_length=100, blank=True)
    billed = models.FloatField(default=0.00)
    paid = models.FloatField(default=0.00)
    details = models.TextField(max_length=500)
    fufiled = models.BooleanField(default=False)
    due_date = models.DateField(blank=True, default=df.date_now())
    open_date = models.DateField(auto_now=True)
    status = models.CharField(max_length=30, default='draft')
    project_id = models.ForeignKey('client.Project',blank=True, null=True, on_delete=models.SET_NULL)
    cupon_id = models.ForeignKey(Coupon,blank=True, null=True, on_delete=models.SET_NULL)
    credit_id = models.ForeignKey(credit,blank=True, null=True, on_delete=models.SET_NULL)
    payment_link = models.URLField(blank=True, null=True)
    payment_type = models.CharField(max_length=30)
    
    def __str__(self):
        ret_str = str(self.id)
        cust_str = str(self.project_id) 
        return ret_str + ' | ' + cust_str

    def get_absolute_url(self):
        return reverse("billing-details", args=(self.id))
    
class LineItem(models.Model):
    
    billing_id = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    amount = models.FloatField(default=5.00) 
    receipt = models.CharField(max_length=400, blank=True)
    time_stamp = models.DateField(auto_created=True)
    item_id = models.CharField(max_length=400, blank=True)
    
    def __str__(self):

        return str(self.item_id)

    def get_absolute_url(self):
        return reverse("payment-details", kwargs=(str(self.item_id)))
    

GalleryProject/site_app/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your Email'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'body' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Message Body'}),
        }

GalleryProject/site_app/views.py
from typing import Any
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.views.generic.edit import FormView
from django.db.models import Q
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Contact, Document
from gallery.models import Image, Dispaly
from client.models import Project, Client
from .forms import ContactForm
from GalleryProject.env.app_Logic.smtp.MailerDJ import AutoReply
from GalleryProject.env.cloudflare_API.CFAPI import APICall
from GalleryProject.env.app_Logic.date_time_calendar import cal_gen, date_passed_check
import random
from pathlib import Path
import os
from dotenv import load_dotenv
from GalleryProject.env.app_Logic.json_utils import DataSetUpdate
from GalleryProject.env.app_Logic.smtp.MailerDJ import AutoReply
from GalleryProject.env.app_Logic.untility.quick_tools import QuickStripe, DateFunction, Hexer
from log_app.logging_config import logging
import time
from random import shuffle
from django.utils.text import slugify
qs = QuickStripe()
df = DateFunction()
hexer = Hexer()
smtp_request = AutoReply()
dataQ = DataSetUpdate()

#-----------------------------------------------------------------------------------------------------------#
#
# functions
#
#-----------------------------------------------------------------------------------------------------------#


def append_cloundflare_id(cf_id, image_id, type_image):
	update_image_record = Image.objects.get(id=image_id)
	
	image_url = 'https://imagedelivery.net/4_y5kVkw2ENjgzV454LjcQ/' + cf_id +'/display'
	update_image_record.image_link = image_url
	update_image_record.save()


#-------------------------------------------------------------------------------------------------------#
# index - booking - galler - about 
#-------------------------------------------------------------------------------------------------------#


def index_page(request):
	all_images = Image.objects.all()
	image_list = Image.objects.filter(display=1)[:50]
	

	image1 = all_images.filter(display=3).first()

	image2 = all_images.filter(display=5).first()

	image3 = all_images.filter(display=7).first()

	return render(request, 'index.html', 
				  {
					'image_list': image_list,
					'image1':image1,
					'image2':image2,
					'image3':image3,
					})

def social_page(request):
	return render(request, 'social.html')

class ContactView(FormView):
	model = Contact
	template_name = 'contact.html'
	form_class = ContactForm
	
	def form_valid(self, form):
		self.object = form.save()
		name = self.object.name
		email = self.object.email
		subject = self.object.subject
		body = self.object.body
		idN = self.object.pk

		email_sent = smtp_request.contact_request(email, name, subject)
		notice_sent = smtp_request.contact_alart(email, name, subject, body)
		if email_sent == 'success' and notice_sent == 'success':

			return redirect('contact-success', pk=idN)
		else:
			e = 'email-sent ', notice_sent, 'notice-sent ', notice_sent
			logging.error("Client Invite Error: %s", str((e)))
			slugified_error_message = slugify(str(e))
			return redirect('issue-backend', status=500, error_message=slugified_error_message)
	
class ContactSuccess(DetailView):
	model = Contact
	template_name = 'success/contact-success.html'
	
def error_logger(request, status, error_message):
	
	return render(request, 'error_page/issue.html', {'status': status, 'e': error_message})
	
#-------------------------------------------------------------------------------------------------------#
# owner panel main branch
#-------------------------------------------------------------------------------------------------------#

def o_main(request):
	image_list = Image.objects.all()
	project_list = Project.objects.all()
	client_list = Client.objects.all()
	gal1 = Image.objects.filter(Q(display=4) | Q(display=3))
	gal2 = Image.objects.filter(Q(display=5) | Q(display=7))
	gal4 = Image.objects.filter(Q(display=6) | Q(display=8))
	site_image = Image.objects.filter(Q(client_id="1"))
	client_images = Image.objects.exclude(Q(client_id="1"))
	dataQ.json_chart_data()

	return render(request, 'o_panel/main.html', {
		'image_list': image_list,
		'project_list': project_list,
		'client_list': client_list,
		'gal1': gal1,
		'gal2': gal2,
		'gal4': gal4,
		'site_image': site_image,
		'client_images':client_images,
	})
	
def o_binder(request):
	month0, month, month2, cal, year, todays_date, cal_date = cal_gen()
	project_list = Project.objects.all()
	client_list = Client.objects.all()
	image_list = Image.objects.all()
	
	return render(request, 'o_panel/binder.html', {
		'image_list': image_list,
		'project_list': project_list,
		'client_list': client_list,
		'year': year,
		'month':month,
	})
	

def marketing(request):
	return render(request, 'o_panel/marketing.html')

def o_gallery(request):
	return render(request, 'o_panel/gallery.html')


def document_settings(request):
	documents = Document.objects.filter(doc_type='site')

GalleryProject/site_app/templates/o_panel/billing/billing-details.html
{% extends 'panel.html' %}
{% block title %}Upload Link{% endblock %}
{% block content %}
{% load static %}
{% if user.is_authenticated %}
<div class='row mt-4 mb-4'>
	<div class='col-6'>
		<div class='sections'>
			<div class='row text-center'>
				<div class='col-4'>
					<h1 class='h1-1'>Total Due</h1>
					<hr>
					<p class='nums'>${{ due|floatformat:2 }}</p>
				</div>
				<div class='col-4'>
					<h1 class='h1-1'>Total paid</h1>
					<hr>
					<p class='nums'>${{ paid|floatformat:2 }}</p>
				</div>
				<div class='col-4'>
					<h1 class='h1-1'>Outstand</h1>
					<hr>
					<p class='nums'>${{ out|floatformat:2 }}</p>
				</div>
				
				<div class='col-12'>
					<div class='sections-2'>
						<div id="dueProgress">
							<div id="due" value="{{ ratio }}"></div>
						</div>
						<h1 class='h1-1 mt-2 mb-2'>{{ ratio }}% Paid</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class='col-3'>
		<div class='sections h-100'>
			<h1 class='h1-1'>{{ invoice.project_id.client_id.user_id.first_name }} {{ invoice.project_id.client_id.user_id.last_name }}</h1>
			<hr>
			<div class='sections-2'>
				<p class='p-p'>Email<br> {{ invoice.project_id.client_id.email }}</p>
				<p class='p-p'>Phone <br> {{ invoice.project_id.client_id.phone }}</p>
				<p class='p-p'>Client ID: {{ invoice.project_id.client_id.id }}</p>
			</div>
		</div>
	</div>

	<div class='col-3 text-center'>
		<div class="sections h-100">					
			<h1 class='h1-1'>
				Status
			</h1>
			<hr>
			<div class="sections-2">
				<div class="loader-box">
					<div class="intern">
						<p class='nums'>
							{{invoice.status}}
						</p>
					</div>
					<div class="external-shadow">
						<div class="sections-sepc spec1">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class='row mt-4'>

	<div class='col-3'>	
		<div class='sections'>
			<h1 class='h1-1'>Invoice Details</h1>
			<hr>

			<div class='sections-2'>
				<div class='row'>
					<div class='col-4'>
						<p class='p-2'>Project</p>
					</div>

					<div class='col-8'>
						<p class='p-p'>{{ invoice.project_id }}</p>
					</div>
					<div class='col-4'>
						<p class='p-2'>Invoice ID:</p>
					</div>

					<div class='col-8'>
						<p class='p-p'>{{ invoice.id }}</p>
					</div>
					<div class='col-4'>
						<p class='p-2'>Payment Type</p>
					</div>

					<div class='col-8'>
						<p class='p-p'>{{ invoice.payment_type}}</p>
					</div>
		
				</div>
			</div>
		</div>
	</div>
		

		

	<div class='col-3'>
		<div class='sections'>
		
			<h1 class='h1-1'>
				Due Date
			</h1>
			<hr>
			<div class='sections-2'>
				<h1 class='h1-1'>
					{{invoice.due_date}}
				</h1>
			</div>
			
		</div>
	</div>

	<div class='col-6'>
		<div class='sections'>
			
			<h1 class='h1-1'>
				Services Provided
		</h1>
			<hr>
			<div class='sections-2'>
				<div class='overflow-auto scroll-menu'>
					<p class='p-p'>{{ invoice.details}}</p>
				</div>
			</div>
		</div>
	</div>

	<div class='col-12 mt-4'>	
		<div class='sections'>
			<h1 class='h1-1'>Line Items</h1>
			<hr>
			<div class='sections-2'>
				<div class='row mt-1'>
					<div class='col-12'>
						<div class='row mt-1 text-center' style='width:95%'>
							<div class='col-3 '>
								<p class="p-p">Line Item</p>
							</div>
							<div class='col-3'>
								<p class="p-p"> Amount</p>
							</div>
							<div class='col-3'>
								<p class="p-p">Line Item ID</p>
							</div>
							<div class='col-3'>
								<p class="p-p">Details</p>
							</div>
						</div>
						<hr>
						<div class="overflow-auto scroll-menu">
						{% for item in line_items %}
							<div class='col-12 text-center' style='width:95%'>
								<div class='row mt-1'>
									<div class='col-3'>
										<p class="p-p">{{ item.receipt }}</p>
									</div>
									<div class='col-3'>
										<p class="p-p">{{ item.amount|floatformat:2 }}</p>
									</div>
									<div class='col-3'>
										<p class="p-p">{{ item.item_id }}</p>
									</div>
									<div class='col-3'>
										<button class="btn-icon" onclick="window.location.href='{% url 'payment-details' item.id %}'">
											<i class="fa-solid fa-file-invoice-dollar"></i>
										</button>
									</div>
								</div>
								<hr>
							</div>
						{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class='row mt-4 sections-small'>
	<div class='col-6 col-md-3 mt-4'>
		<div class='bookcard text-center' onclick="window.location.href='#'">
			<i class="fa-solid fa-file-lines fa-2xl"></i>
			<p class='mt-2'>Edit Invoice</p>
		</div>
	</div>
	<div class='col-6 col-md-3 mt-4'>
		<form method="post" action="{% url 'billing-details' invoice.id %}">
			{% csrf_token %}
			<button class='btn-cust text-center'  type="submit" name="cash" value="Cash" style='width:100%'>
				<i class="fa-solid fa-money-bill-1-wave fa-2xl"></i>
				<p class='mt-2'>Mark Paid in Cash</p>
			</button>
		</form>
	</div>
	<div class='col-6 col-md-3 mt-4'>
		<form method="post" action="{% url 'billing-details' invoice.id %}">
			{% csrf_token %}
			<button class='btn-cust text-center'  type="submit" name="open" value="Open" style='width:100%'>
				<i class="fa-solid fa-file-invoice-dollar fa-2xl"></i>
				<p class='mt-2'>Send Invoice</p>
			</button>
		</form>
	</div>
	<div class='col-6 col-md-3 mt-4'>
		<form method="post" action="{% url 'billing-details' invoice.id %}">
			{% csrf_token %}
			<button class='btn-cust text-center'  type="submit" name="delete" value="Delete" style='width:100%'>
				<i class="fa-regular fa-file-lines fa-2xl"></i>
				<p class='mt-2'>Void Invoice</p>
			</button>
		</form>
	</div>
</div>

{% endif %}
<script src={% static 'js/invoiceBar.js' %}></script>
{% endblock %}

GalleryProject/site_app/templates/o_panel/billing/create-invoice.html
{% extends 'panel.html' %}
{% block title %}Crate Invoice{% endblock %}
{% block content %}
{% load static %}
<div class="sections p-p form-group">
    <h1 class='h1-1'>Invoice Details</h1>
    <hr>
        
    <form method=POST>
        {% csrf_token %}
        <div class='sections-2'>

            <div class='row'>
                <div class='col-6'>
                    <label for="id_due_date">Due date:</label>
                    <input type="date" name="due_date" class="form-control" id="id_due_date">
                
                    <label for="id_project_id">Project id:</label>
                    <select name="project_id" class="form-control" required="" id="id_project_id">
                        <option value="" selected="">---------</option>
                        {% for project in project_list %}
                        <option value="{{project.id}}">{{project}}</option>
                        
                        {%endfor%}
                        
                    </select>
                    <label for="id_payment_type">Payment type:</label>
                    <select name="payment_type" class="form-control" maxlength="30" id="id_payment_type">
                        <option value="Project Invoice">Project Invoice</option>
                        <option value="Item Invoice">Item Invoice</option>
                        <option value="Travle Cost">Travle Cost</option>
                        <option value="Overnight Stayt Cost">Overnight Stayt Cost</option>
                    </select>
                </div>
                <div class='col-6'>
                    <label for="id_details">Details:</label>
                    <textarea name="details" rows="6" class="form-control" maxlength="500" required="" id="id_details"></textarea>
                </div>


            </div>
        </div>
		<div class='section-small'>
			<h1 class='h1-1 mt-4'>Line items</h1>
			<hr>

			<div class='col-12'>
				<div class="row">
					<div class='col-12'>
						<p class='p-p'>Add Line Items</p>
						<i type="button" class='btn-icon fa-solid fa-plus mb-4' onclick="newItem()" ></i>
					</div>  

				</div>
				
				<div class="row">
					<div class='col-12'>
						<div class='section-scroll overflow-auto' id='itemSection'>
							<div class="row" id='lineItems' style='width:95%'>
								<div class="col-5">
									<p class='p-p'>
										Line item amount
									</p>
								</div>
								<div class="col-5">
									<p class='p-p'>
										Line item description
									</p>
								</div>
								<div class="col-2 text-center">
									<p class='p-p'>
										Remove
									</p>
								</div>
								<hr>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>

            
        <h1 class='h1-1 mt-4'>Finalize Details</h1>
        <hr>
        
        <div class='section-small'>
            <div class="row">
                <div class='col-4'>
                    <div class="row">
                        <div class='col-6'>
                            <div class=" form-check form-switch">
                                <label class="form-check-label" for="id_open">Open</label>
                                <input class="form-check-input" type="checkbox" name="open" id="id_open" value='yes'>
                            </div>
                        </div>
                        <div class='col-6'>
                            <div class="form-check form-switch">
                                <label class="form-check-label" for="id_paidCash">Paid</label>
                                <input class="form-check-input" type="checkbox" name="paidCash" id="id_paidCash" value='yes'>
                            </div>
                        </div>

                        <div class='col-6'>
                            <i class="btn-icon fa-solid fa-circle-info" type="button" data-bs-toggle="collapse" data-bs-target="#openInfo" aria-expanded="false" aria-controls="openInfo">
                            </i>
                        </div>
                        <div class='col-6'>
                            <i class="btn-icon fa-solid fa-circle-info" type="button" data-bs-toggle="collapse" data-bs-target="#paidInfo" aria-expanded="false" aria-controls="paidInfo">
                            </i>
                        </div>
                    </div>
                    <div class="collapse" id="paidInfo" style='width:100%'>
                        <p class='p-p mt-4  mb-4'>
                            Was this paid in cash or outside of this site, if so toggle
                            <b>Paid</b> to <b>On</b>. Doing so will show this item as paid.
                        </p>
                    </div>
                    <div class="collapse" id="openInfo" style='width:100%'>
                        <p class='p-p mt-4 mb-4'>
                            By defualt all invoices are marked as <b>Drafts</b>, 
                            to mark the invoice as <b>Open</b> toggle open to <b>On</b>. 
                            Doing so will send the invoice to the customer.
                        </p>
                    </div>
                </div>
                <div class='col-8 text-center'> 
                    <h1 class='h1-1 mt-4'>Total Billed</h1>
                    <h1 class='nums' id='total'></h1>
                </div>
            </div>
			<button class='btn-cust mt-4' id='addLoader'>submit</button>
        </div>
       
    </form>
</div>

<script src="{% static 'js/invoice.js' %}"></script>


{% endblock %}